apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simplebank-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"

spec:
  ingressClassName: nginx

  # tls:
  #   - hosts:
  #       - your-domain.com   # 🔥 Replace later
  #     secretName: tls-secret

  rules:
    - host: your-domain.com   # 🔥 Replace later
      http:
        paths:

          # ✅ Auth
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 80

          # ✅ Gateway APIs
          - path: /api/gateway
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 80

          # ✅ UI
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-ui-service
                port:
                  number: 80